_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/R-50.pkl"
  SPARSE_INST:
    DECODER:
      NAME: "GroupIAMSoftDecoder"
  OWIS:
    HIDDEN_DIM: 1024
OUTPUT_DIR: "output/sparse_inst_r50_giam_soft"