_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/R-50.pkl"
  OWIS:
    HIDDEN_DIM: 256
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MASK_FORMAT: "polygon"
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 5e-5
  STEPS: (210000, 250000)
  MAX_ITER: 22000
  WEIGHT_DECAY: 0.05
OUTPUT_DIR: "output/sparse_inst_r50_aug"