_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/R-50.pkl"
  OWIS:
    HIDDEN_DIM: 256
  SPARSE_INST:
    DECODER:
      NAME: "GroupIAMSoftDecoder"
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MASK_FORMAT: "polygon"
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.00005
  STEPS: (30000, 60000)
  MAX_ITER: 90000 
  WEIGHT_DECAY: 0.05
SOLVER:
  AMP:
    ENABLED: True
OUTPUT_DIR: "output/sparse_inst_r50_aug_fp16"