_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/R-50.pkl"
  OWIS:
    HIDDEN_DIM: 256
  SPARSE_INST:
    ENCODER:
      NAME: "InstanceContextEncoder"
    DECODER:
      NAME: "GroupIAMSoftDecoder"
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MASK_FORMAT: "polygon"
SOLVER:
  AMP:
    ENABLED: True
OUTPUT_DIR: "output/sparse_inst_r50_aug_fp16"