_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/R-50.pkl"
  OWIS:
    HIDDEN_DIM: 1024
    PREV_INTRODUCED_CLS: 40
    CUR_INTRODUCED_CLS: 20
    HIDDEN_DIM: 1024
    EMPTY_WEIGHT: 0.001
    UNMATCH_WEIGHT: 0.00001
    MEMORY_BANK_SIZE: 1000
    CALIBRATION_TEMPERATURE: 1.0
    OBJECTNESS_THRESHOLD: 0.45
    CONTRASTIVE_LOSS_WEIGHT: 1
    UNKNOWN_LOSS_WEIGHT: 0.5
DATASETS:
  TRAIN: ("coco_train_T3",)
  TEST:  ("coco_val_T3",)
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.00005
  STEPS: (10000, 18000, 24000)
  MAX_ITER: 27000
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MASK_FORMAT: "polygon"
OUTPUT_DIR: "output/t3"