_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/R-50.pkl"
  OWIS:
    HIDDEN_DIM: 1024
    PREV_INTRODUCED_CLS: 0
    CUR_INTRODUCED_CLS: 20
DATASETS:
  TRAIN: ("coco_train_T1",)
  TEST:  ("coco_val_T1",)
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MASK_FORMAT: "polygon"
OUTPUT_DIR: "output/sparse_inst_r50_giam_aug"