_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/R-50.pkl"
  OWIS:
    HIDDEN_DIM: 1024
    PREV_INTRODUCED_CLS: 0
    CUR_INTRODUCED_CLS: 0
    EMPTY_WEIGHT: 0.1
    UNMATCH_WEIGHT: 0.001
    MEMORY_BANK_SIZE: 1000
    CALIBRATION_TEMPERATURE: 1.0
    OBJECTNESS_THRESHOLD: 0.2
    CONTRASTIVE_LOSS_WEIGHT: 1
    UNKNOWN_LOSS_WEIGHT: 1.5
DATASETS:
  TRAIN: ("coco_train_T0",)
  TEST:  ("coco_val_T0",)
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MASK_FORMAT: "polygon"
OUTPUT_DIR: "output/sparse_inst_r50_giam_aug"