_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/R-50.pkl"
  OWIS:
    HIDDEN_DIM: 1024
    PREV_INTRODUCED_CLS: 0
    CUR_INTRODUCED_CLS: 20
    EMPTY_WEIGHT: 0.1
    UNMATCH_WEIGHT: 0.005
    MEMORY_BANK_SIZE: 1000
    CALIBRATION_TEMPERATURE: 1.0
    OBJECTNESS_THRESHOLD: 0.25
    CONTRASTIVE_LOSS_WEIGHT: 1
    UNKNOWN_LOSS_WEIGHT: 1.2
DATASETS:
  TRAIN: ("coco_train_T1",)
  TEST:  ("coco_val_T1",)
SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.00005
  STEPS: (50000, 80000, 110000)
  MAX_ITER: 130000
  WEIGHT_DECAY: 0.01
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MASK_FORMAT: "polygon"
OUTPUT_DIR: "output/t1"