_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/R-50.pkl"
  OWIS:
    HIDDEN_DIM: 1024
    PREV_INTRODUCED_CLS: 40
    CUR_INTRODUCED_CLS: 20
    EMPTY_WEIGHT: 0.01
    CALIBRATION_TEMPERATURE: 1.0
    OBJECTNESS_THRESHOLD: 0.35
    CONTRASTIVE_LOSS_WEIGHT: 1
    UNKNOWN_LOSS_WEIGHT: 0.5
DATASETS:
  TRAIN: ("coco_train_T3",)
  TEST:  ("coco_val_T3",)
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MASK_FORMAT: "polygon"
OUTPUT_DIR: "output/t3"